Product Class Changes
AndrezaEmiliano/bicycleShopBackend pull request #1
Opened 2020-07-21 14:33 UTC by AndrezaEmiliano

2020-07-21 15:47 UTC, alexandre-exacta requested changes

2020-07-21 15:47 UTC, alexandre-exacta commented on src/Products.java
> +        Products.totalProduct++;
Isso aqui funciona mesmo? Ja testou instanciar mais de um produto e ver como fica essa quantidade total? Ex um produto luva e um produto capacete com totais diferentes.

2020-07-21 15:47 UTC, alexandre-exacta commented on src/Products.java
> +            System.out.println("O preço do produto não pode ser negativo, portanto o preço não foi cadastrado");
Não faria mais sentido usar uma Exception aqui? Porque simplesmente dar um SysOut não impede instanciar um novo produto com preço negativo. Nesse cenário aqui, o produto ficou com preço nulo.

2020-07-21 15:47 UTC, alexandre-exacta commented on src/Products.java
> +    public void setPrice() {
Indo de encontro da validação que você colocou no construtor de preço negativo, se eu chamar o metodo setPrice(-10.00), eu não burlo sua validação?

2020-07-21 15:47 UTC, alexandre-exacta commented on src/Products.java
> +    public void editName(String newName){
Na prática, qual a diferença desse método para o setName? Não fazem a mesma coisa? Exceto pela parte de checar se o nome mudou ou não.

2020-07-21 15:47 UTC, alexandre-exacta commented on src/Products.java
> +    public void discount (BigDecimal percentDiscount) {
Para manter o padrão, faz sentido chamar esse metodo de setDiscount?

2020-07-21 17:51 UTC, AndrezaEmiliano commented on src/Products.java
> +        Products.totalProduct++;
Funciona sim, pelo menos quando eu testei, funcionou. No classe Clients também coloquei e também funcionou.

2020-07-22 12:58 UTC, AndrezaEmiliano commented on src/Products.java
> +            System.out.println("O preço do produto não pode ser negativo, portanto o preço não foi cadastrado");
Então, eu tinha colocado a exception aqui, mas pelos testes que fiz, ela não mudava nada no programa, ai somente onde chamava o preço do produto que eu coloquei a exception. 
Basicamente a exception não "trata" o problema, ela só avisa o usuário de quem tem um problema se ele fizer assim e previne do programa terminar, é isso?
Eu pensei em como fazer diferente disso, mas não sei, talvez colocar um else if falando que o preço do produto não pode ser null? Porque realmente, se a pessoa colocar um valor negativo, o preço fica null, por isso coloquei exceptions onde chamava o preço, para não dar null pointer.

2020-07-22 12:59 UTC, AndrezaEmiliano commented on src/Products.java
> +    public void setPrice() {
Burla. Nisso eu não tinha pensado. O que eu posso fazer é colocar a mesma rega que coloquei no construtor. Mas ai vou repetir o código, isso não é boa prática, certo?

2020-07-22 13:01 UTC, AndrezaEmiliano commented on src/Products.java
> +    public void editName(String newName){
Realmente não tem muita diferença. Devo deixar esse método e chamá-lo de setName, ou apagar e deixar só o setName que já existe?

2020-07-22 13:02 UTC, AndrezaEmiliano commented on src/Products.java
> +    public void discount (BigDecimal percentDiscount) {
Faz total sentido. Vou tentar começar a pensar assim. Obrigada.

2020-07-22 13:48 UTC, alexandre-exacta commented on src/Products.java
> +        Products.totalProduct++;
A ideia é ser um total de todos os produtos?

2020-07-22 13:50 UTC, alexandre-exacta commented on src/Products.java
> +    public void setPrice() {
Tem um jeito de não duplicar o código.

Dica: a validação ficaria em apenas 1 dos métodos

2020-07-22 13:50 UTC, alexandre-exacta commented on src/Products.java
> +    public void editName(String newName){
Melhor manter o setName por conta do padrão JavaBeans que comentamos. Idealmente esse tipo de lógica iria em outro lugar que veremos mais para frente :)

2020-07-22 13:54 UTC, AndrezaEmiliano commented on src/Products.java
> +        Products.totalProduct++;
Isso, total de produtos cadastrados e total de clientes cadastrados.

2020-07-22 13:55 UTC, alexandre-exacta commented on src/Products.java
> +        Products.totalProduct++;
Entendi, confundi com o outro atributo de quantidade de produto (quantityProduct). Então funciona mesmo :)

2020-07-22 13:57 UTC, alexandre-exacta commented on src/Products.java
> +            System.out.println("O preço do produto não pode ser negativo, portanto o preço não foi cadastrado");
Considerando o que sabemos até o momento, o ideal é que o programa termine se alguem tentar instanciar um produto com preço negativo (ou seja, throw new Exception)

2020-07-22 14:54 UTC, AndrezaEmiliano commented on src/Products.java
> +        Products.totalProduct++;
Acha melhor trocar o nome, para não ficar confuso?

2020-07-22 14:54 UTC, AndrezaEmiliano commented on src/Products.java
> +            System.out.println("O preço do produto não pode ser negativo, portanto o preço não foi cadastrado");
okay

2020-07-22 14:55 UTC, alexandre-exacta commented on src/Products.java
> +        Products.totalProduct++;
Não precisa, eu que fiz confusão mesmo

2020-07-22 17:12 UTC, AndrezaEmiliano commented on src/Products.java
> +        Products.totalProduct++;
okay

2020-07-22 17:12 UTC, AndrezaEmiliano commented on src/Products.java
> +    public void editName(String newName){
okay

2020-07-30 12:53 UTC, ghost requested changes

2020-07-30 12:53 UTC, gilsonexacta commented on src/Products.java
> +        validatePrice (price);
Aqui ficaria mais lógico chamar o setPrice ao invés do validatePrice.

2020-07-30 12:53 UTC, gilsonexacta commented on src/Products.java
> +            }
Pensando no futuro, este tipo de implementação ficaria mais fácil de ser testada invertendo a lógica e removendo o else. Outro detalhe é verificar o parâmetro price e a identação do código.
```
if (price != null && price.doubleValue() <0) {
    throw new PriceException ("O preço do produto não pode ser negativo! O preço atual do produto é " + getPrice());
}
this.price = price;
```

2020-08-03 15:02 UTC, AndrezaEmiliano commented on src/Products.java
> +        validatePrice (price);
Okay.
É que eu pensei que não poderia colocar a exception dentro do set, mas a estrutura é similar mesmo. Vou trocar.

2020-08-03 15:02 UTC, AndrezaEmiliano commented on src/Products.java
> +            }
Compreendido.

2020-08-06 11:19 UTC, ghost requested changes

2020-08-06 11:19 UTC, gilsonexacta commented on src/Products.java
> +        }
O preço poderá ser nulo?

2020-08-06 11:19 UTC, gilsonexacta commented on src/Products.java
> +        System.out.println("O novo valor do produto com o desconto de " + percentDiscount + "% concedido é: R$" + getPrice());
Existe necessidade desta linha?

2020-08-06 11:30 UTC, AndrezaEmiliano commented on src/Products.java
> +        }
Poder não pode, porque quando os cálculos forem realizados terá problemas. Vou pensar em como tratar isso.

2020-08-06 11:31 UTC, AndrezaEmiliano commented on src/Products.java
> +        System.out.println("O novo valor do produto com o desconto de " + percentDiscount + "% concedido é: R$" + getPrice());
A linha de impressão? Ou o método todo?
A linha de impressão era para eu ver quando rodava o programa.

2020-08-06 11:37 UTC, gilsonexacta commented on src/Products.java
> +        System.out.println("O novo valor do produto com o desconto de " + percentDiscount + "% concedido é: R$" + getPrice());
Ok, mas o ideal é que ela esteja presente no seu teste então e não no modelo da sua aplicação. Para isto existe outros itens que não viram ainda, que seria adição de logs.
Neste momento acho que faz mais sentido esta linha estar fora desta classe.

2020-08-07 18:54 UTC, ghost approved these changes

2020-08-14 18:04 UTC, alexandre-exacta approved these changes

2020-08-14 18:52 UTC, merged