Creating ProductCategory Class
AndrezaEmiliano/bicycleShopBackend pull request #2
Opened 2020-07-21 17:08 UTC by AndrezaEmiliano

2020-07-21 20:18 UTC, ghost requested changes

2020-07-21 20:18 UTC, gilsonexacta commented on src/ProductCategory.java
> +    private String category;
Não faz mais sentido este atributo se chamar name? em uma futura utilização ficaria algo do tipo
productCategory.getName()

2020-07-22 13:03 UTC, AndrezaEmiliano commented on src/ProductCategory.java
> +    private String category;
Faz sentido sim, não tinha pensado "no futuro" como chamar o método. Vou tentar me lembrar disso. Obrigada.

2020-07-30 12:42 UTC, ghost approved these changes

2020-08-14 18:53 UTC, merged