Creating Address Class
AndrezaEmiliano/bicycleShopBackend pull request #5
Opened 2020-07-21 17:28 UTC by AndrezaEmiliano

2020-07-21 20:30 UTC, ghost requested changes

2020-07-21 20:30 UTC, gilsonexacta commented on src/Address.java
> +    private String stAve;
stAve...seria streetAvenue? talvez streetName ficaria melhor....só opinião...

2020-08-06 11:32 UTC, ghost approved these changes

2020-08-14 18:07 UTC, alexandre-exacta approved these changes

2020-08-14 18:53 UTC, merged