Creating Invoice Class
AndrezaEmiliano/bicycleShopBackend pull request #7
Opened 2020-07-21 17:37 UTC by AndrezaEmiliano

2020-07-21 20:35 UTC, ghost requested changes

2020-07-21 20:35 UTC, gilsonexacta commented on src/Invoice.java
> +    private long barcode;
faz sentido o barcode ser long???

2020-07-22 14:26 UTC, alexandre-exacta commented on src/Invoice.java
> +        this.deadline = LocalDate.now().plusDays(2);
SHOW!

2020-08-14 18:12 UTC, alexandre-exacta requested changes

2020-08-14 18:12 UTC, alexandre-exacta commented on src/Invoice.java
> +public class Invoice extends PaymentMethod {
Como sugestão, invoice está relacionado a nota fiscal (ou recibo). Sugiro mudar o nome da classe para BankSlip

2020-08-14 18:59 UTC, AndrezaEmiliano commented on src/Invoice.java
> +public class Invoice extends PaymentMethod {
Então, aqui eu coloquei invoice, porque eu perguntei para uma amiga minha que tem empresa nos eua e ela disse que boleto nosso aqui é invoice para eles lá. Ai por isso achei correto colocar.

2020-08-14 19:15 UTC, alexandre-exacta commented on src/Invoice.java
> +public class Invoice extends PaymentMethod {
Para nós aqui fica ambiguo. Na verdade, esse conceito de boleto bancário que tem um código que ja registra o pagamento automaticamente que eu saiba nem existe nos EUA.

Todos os sistemas que ja trabalhei sempre usamos bank slip. Pode ser que tenha algum termo melhor.

2020-08-14 19:29 UTC, AndrezaEmiliano commented on src/Invoice.java
> +public class Invoice extends PaymentMethod {
Entendi. Já mudei =D

2020-08-17 17:46 UTC, alexandre-exacta approved these changes

2020-08-17 17:50 UTC, merged